/**
 * @file    dtmf_secure_access.c
 * @brief   Secure Access System using DTMF Tone Detection
 *
 * Detects DTMF tones via a MEMS microphone using FFT analysis on an
 * STM32 Nucleo-L476RG board. Validates a 4-digit passcode and provides
 * LED + audio feedback via a DAC-driven speaker.
 *
 * Hardware:
 *   - STM32 Nucleo-L476RG (64-pin)
 *   - ICS-40180 MEMS Microphone Breakout (analog output → PA0 / ADC1_IN5)
 *   - PAM8302 Class-D Audio Amplifier + 8Ω mono speaker
 *
 * Peripherals used:
 *   - ADC1  – audio sampling (DMA, triggered by TIM6)
 *   - TIM6  – 20 kHz sampling clock
 *   - DAC1  – audio feedback output
 *   - DMA   – ADC→RAM and RAM→DAC transfers
 *   - EXTI  – on-board blue push-button (PC13)
 *
 * Build requirements:
 *   - CMSIS DSP library (arm_math.h, arm_rfft_fast_f32)
 *   - STM32 HAL drivers
 *
 * SPDX-License-Identifier: MIT
 */

/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "arm_math.h"
#include <stdio.h>
#include <string.h>
#include <math.h>

/* =========================================================================
 * Configuration
 * =========================================================================*/

/* FFT / sampling */
#define FFT_FULL_SIZE     2048u   /**< Must be a power of 2                 */
#define FFT_HALF_SIZE     (FFT_FULL_SIZE / 2u)
#define SAMPLE_RATE_HZ    20000u  /**< ADC sampling rate (Hz)               */

/* Passcode */
#define PASSCODE_LENGTH   4u      /**< Number of DTMF digits in the code    */

/* DTMF detection */
#define FREQ_TOLERANCE_HZ 50.0f   /**< ±Hz window around each standard tone */
#define MIN_MAGNITUDE     10.0f   /**< Ignore peaks below this threshold    */

/* Audio feedback */
#define BEEP_FREQ_HZ      1000u   /**< Success tone (Hz)                    */
#define BUZZ_FREQ_HZ      300u    /**< Error tone (Hz)                      */
#define BEEP_DURATION_MS  500u
#define BUZZ_DURATION_MS  500u
#define BEEP_SAMPLES      ((SAMPLE_RATE_HZ * BEEP_DURATION_MS) / 1000u)
#define BUZZ_SAMPLES      ((SAMPLE_RATE_HZ * BUZZ_DURATION_MS) / 1000u)

/* Timing */
#define DEBOUNCE_MS       200u    /**< Minimum ms between button presses    */
#define LED_ON_MS         2000u   /**< LED-on duration for correct passcode */
#define BLINK_PERIOD_MS   100u    /**< LED blink half-period (5 Hz → 100 ms)*/
#define BLINK_COUNT       5u      /**< Number of blinks for wrong passcode  */

/* UART debug (set to 0 to disable) */
#define DEBUG_UART_ENABLED 1

/* =========================================================================
 * DTMF Frequency Tables
 * =========================================================================*/

/** Standard DTMF row (low) frequencies in Hz */
static const float32_t ROW_FREQS[4] = { 697.0f, 770.0f, 852.0f, 941.0f };

/** Standard DTMF column (high) frequencies in Hz */
static const float32_t COL_FREQS[4] = { 1209.0f, 1336.0f, 1477.0f, 1633.0f };

/** DTMF 4×4 keypad character map */
static const char DTMF_KEYPAD[4][4] = {
    { '1', '2', '3', 'A' },
    { '4', '5', '6', 'B' },
    { '7', '8', '9', 'C' },
    { '*', '0', '#', 'D' }
};

/* =========================================================================
 * Private Variables
 * =========================================================================*/

/* Audio processing buffers */
static uint16_t  adcRawBuffer[FFT_FULL_SIZE];
static float32_t normalizedSignal[FFT_FULL_SIZE];
static float32_t fftOutput[FFT_FULL_SIZE];        /* Complex FFT output     */
static float32_t fftMagnitudes[FFT_HALF_SIZE];
static float32_t frequencyBins[FFT_HALF_SIZE];

/* Audio feedback buffers */
static uint16_t beepBuffer[BEEP_SAMPLES];
static uint16_t buzzBuffer[BUZZ_SAMPLES];

/* ARM DSP FFT instance */
static arm_rfft_fast_instance_f32 fftInstance;

/* Passcode state */
static const char  CORRECT_PASSCODE[PASSCODE_LENGTH] = { '1', '2', '3', '4' };
static char        enteredDigits[PASSCODE_LENGTH];
static uint8_t     digitPosition  = 0;
static uint8_t     codeComplete   = 0;

/* ISR flags (volatile = read by both ISR and main loop) */
static volatile uint8_t buttonPressed = 0;
static volatile uint8_t signalReady   = 0;

/* =========================================================================
 * External Peripheral Handles (generated by STM32CubeMX)
 * =========================================================================*/
extern ADC_HandleTypeDef  hadc1;
extern DAC_HandleTypeDef  hdac1;
extern DMA_HandleTypeDef  hdma_dac_ch1;
extern TIM_HandleTypeDef  htim6;
extern UART_HandleTypeDef huart2;

/* =========================================================================
 * Private Function Prototypes
 * =========================================================================*/
static void     System_Init(void);
static void     GenerateBeepTone(void);
static void     GenerateBuzzTone(void);
static void     PlaySound(const uint16_t *buffer, uint32_t length);
static void     ProcessAudioSignal(void);
static char     DetectDTMFKey(void);
static int      FindNearestFreq(const float32_t *table, int count, float32_t freq, float32_t *diff);
static void     ValidatePasscode(void);
static void     HandleLEDFeedback(uint8_t isCorrect);
static void     System_DebugLog(const char *msg);
static float32_t FindPeakInRange(float32_t freqLow, float32_t freqHigh, int *peakBinOut);

/* =========================================================================
 * Main Entry Point
 * =========================================================================*/

int main(void)
{
    /* HAL + peripheral init (generated by CubeMX) */
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_DMA_Init();
    MX_USART2_UART_Init();
    MX_ADC1_Init();
    MX_DAC1_Init();
    MX_TIM6_Init();

    System_Init();

    /* Main loop */
    while (1)
    {
        if (signalReady)
        {
            signalReady = 0;
            ProcessAudioSignal();

            if (codeComplete)
            {
                codeComplete = 0;
                ValidatePasscode();
            }
        }
    }
}

/* =========================================================================
 * System Initialisation
 * =========================================================================*/

/**
 * @brief  One-time setup: FFT, frequency bins, audio buffers, timer, LED.
 */
static void System_Init(void)
{
    /* Initialise ARM DSP FFT instance */
    arm_rfft_fast_init_f32(&fftInstance, FFT_FULL_SIZE);

    /* Pre-calculate FFT bin centre frequencies */
    for (uint32_t i = 0; i < FFT_HALF_SIZE; i++)
    {
        frequencyBins[i] = (float32_t)i * SAMPLE_RATE_HZ / (float32_t)FFT_FULL_SIZE;
    }

    /* Pre-generate audio feedback waveforms */
    GenerateBeepTone();
    GenerateBuzzTone();

    /* Start the TIM6 timebase used by the ADC trigger */
    HAL_TIM_Base_Start(&htim6);

    /* LED off at startup */
    HAL_GPIO_WritePin(LD2_GPIO_Port, LD2_Pin, GPIO_PIN_RESET);

    System_DebugLog("DTMF Secure Access System initialised.\r\n");
    System_DebugLog("Waiting for button press...\r\n");
}

/* =========================================================================
 * HAL Callbacks (called from IRQ context)
 * =========================================================================*/

/**
 * @brief  EXTI callback – blue user button (PC13).
 *         Starts ADC-DMA capture if still accepting digits.
 */
void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
    static uint32_t lastPressTime = 0;
    uint32_t now = HAL_GetTick();

    /* Software debounce */
    if ((now - lastPressTime) < DEBOUNCE_MS)
        return;
    lastPressTime = now;

    /* Only start a capture if we still need digits */
    if (digitPosition < PASSCODE_LENGTH)
    {
        buttonPressed = 1;
        HAL_ADC_Start_DMA(&hadc1, (uint32_t *)adcRawBuffer, FFT_FULL_SIZE);
    }
}

/**
 * @brief  ADC DMA complete callback – stop DMA and normalise samples.
 *         Converts 12-bit unsigned ADC values to ±1.0 float.
 */
void HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef *hadc)
{
    if (hadc->Instance != ADC1)
        return;

    HAL_ADC_Stop_DMA(&hadc1);
    buttonPressed = 0;

    /* Convert [0, 4095] → [-1.0, +1.0] */
    for (uint32_t i = 0; i < FFT_FULL_SIZE; i++)
    {
        normalizedSignal[i] = ((float32_t)adcRawBuffer[i] - 2048.0f) / 2048.0f;
    }

    signalReady = 1;
}

/* =========================================================================
 * Audio Signal Processing
 * =========================================================================*/

/**
 * @brief  Run real FFT on normalised audio and compute magnitude spectrum.
 */
static void ProcessAudioSignal(void)
{
    /* Real FFT: normalizedSignal → fftOutput (interleaved Re/Im) */
    arm_rfft_fast_f32(&fftInstance, normalizedSignal, fftOutput, 0);

    /* Compute magnitude of each complex bin */
    for (uint32_t i = 0; i < FFT_HALF_SIZE; i++)
    {
        float32_t re = fftOutput[2u * i];
        float32_t im = fftOutput[2u * i + 1u];
        fftMagnitudes[i] = sqrtf(re * re + im * im);
    }

    /* Attempt to identify a DTMF digit */
    char key = DetectDTMFKey();

    if (key != '\0' && digitPosition < PASSCODE_LENGTH)
    {
        enteredDigits[digitPosition++] = key;

        char msg[48];
        snprintf(msg, sizeof(msg), "Digit %u: %c\r\n", (unsigned)digitPosition, key);
        System_DebugLog(msg);

        if (digitPosition == PASSCODE_LENGTH)
            codeComplete = 1;
    }
    else if (key == '\0')
    {
        System_DebugLog("No DTMF tone detected.\r\n");
    }
}

/**
 * @brief  Scan magnitude spectrum for DTMF row/column peaks and identify key.
 * @return Detected character, or '\0' if detection failed.
 */
static char DetectDTMFKey(void)
{
    int rowBin = -1, colBin = -1;

    /* Find dominant peak in the row-frequency band (650–960 Hz) */
    float32_t rowMag = FindPeakInRange(650.0f, 960.0f, &rowBin);

    /* Find dominant peak in the column-frequency band (1170–1660 Hz) */
    float32_t colMag = FindPeakInRange(1170.0f, 1660.0f, &colBin);

    /* Require a minimum magnitude to rule out noise */
    if (rowMag < MIN_MAGNITUDE || colMag < MIN_MAGNITUDE)
        return '\0';

    float32_t rowFreq = frequencyBins[rowBin];
    float32_t colFreq = frequencyBins[colBin];

    /* Match detected frequencies to nearest standard DTMF frequencies */
    float32_t rowDiff, colDiff;
    int row = FindNearestFreq(ROW_FREQS, 4, rowFreq, &rowDiff);
    int col = FindNearestFreq(COL_FREQS, 4, colFreq, &colDiff);

    if (row < 0 || col < 0 ||
        rowDiff > FREQ_TOLERANCE_HZ || colDiff > FREQ_TOLERANCE_HZ)
    {
        return '\0';
    }

    char key = DTMF_KEYPAD[row][col];

    char msg[64];
    snprintf(msg, sizeof(msg),
             "Row %.0f Hz, Col %.0f Hz → key '%c'\r\n",
             (double)rowFreq, (double)colFreq, key);
    System_DebugLog(msg);

    return key;
}

/**
 * @brief  Return the magnitude of the largest FFT bin in [freqLow, freqHigh].
 * @param[out] peakBinOut  Index of the peak bin (set only if peak found).
 * @return Magnitude of the peak, or 0.0f if no bin falls in the range.
 */
static float32_t FindPeakInRange(float32_t freqLow, float32_t freqHigh, int *peakBinOut)
{
    float32_t maxMag = 0.0f;
    int        best   = -1;

    for (uint32_t i = 0; i < FFT_HALF_SIZE; i++)
    {
        float32_t f = frequencyBins[i];
        if (f >= freqLow && f <= freqHigh)
        {
            if (fftMagnitudes[i] > maxMag)
            {
                maxMag = fftMagnitudes[i];
                best   = (int)i;
            }
        }
    }

    if (best >= 0)
        *peakBinOut = best;

    return maxMag;
}

/**
 * @brief  Find the index of the standard frequency closest to @p freq.
 * @param[out] diff  Absolute difference between @p freq and the nearest entry.
 * @return Index into @p table, or -1 if @p table is empty.
 */
static int FindNearestFreq(const float32_t *table, int count,
                            float32_t freq, float32_t *diff)
{
    int   best    = -1;
    float minDiff = 1e9f;

    for (int i = 0; i < count; i++)
    {
        float d = fabsf(table[i] - freq);
        if (d < minDiff)
        {
            minDiff = d;
            best    = i;
        }
    }

    *diff = minDiff;
    return best;
}

/* =========================================================================
 * Passcode Validation & Feedback
 * =========================================================================*/

/**
 * @brief  Compare entered digits against the stored passcode and give feedback.
 */
static void ValidatePasscode(void)
{
    char dbg[64];
    snprintf(dbg, sizeof(dbg),
             "Validating: %c%c%c%c\r\n",
             enteredDigits[0], enteredDigits[1],
             enteredDigits[2], enteredDigits[3]);
    System_DebugLog(dbg);

    uint8_t correct = 1;
    for (uint8_t i = 0; i < PASSCODE_LENGTH; i++)
    {
        if (enteredDigits[i] != CORRECT_PASSCODE[i])
        {
            correct = 0;
            break;
        }
    }

    HandleLEDFeedback(correct);

    /* Reset for the next attempt */
    digitPosition = 0;
    memset(enteredDigits, 0, sizeof(enteredDigits));
}

/**
 * @brief  Provide LED and audio feedback after passcode validation.
 * @param  isCorrect  Non-zero → correct passcode; 0 → wrong.
 *
 * Correct:  Beep + LED on for LED_ON_MS.
 * Wrong:    Buzz + LED blinks BLINK_COUNT times at 5 Hz.
 */
static void HandleLEDFeedback(uint8_t isCorrect)
{
    if (isCorrect)
    {
        System_DebugLog("ACCESS GRANTED\r\n");
        PlaySound(beepBuffer, BEEP_SAMPLES);
        HAL_GPIO_WritePin(LD2_GPIO_Port, LD2_Pin, GPIO_PIN_SET);
        HAL_Delay(LED_ON_MS);
    }
    else
    {
        System_DebugLog("ACCESS DENIED\r\n");
        PlaySound(buzzBuffer, BUZZ_SAMPLES);
        for (uint8_t i = 0; i < BLINK_COUNT; i++)
        {
            HAL_GPIO_WritePin(LD2_GPIO_Port, LD2_Pin, GPIO_PIN_SET);
            HAL_Delay(BLINK_PERIOD_MS);
            HAL_GPIO_WritePin(LD2_GPIO_Port, LD2_Pin, GPIO_PIN_RESET);
            HAL_Delay(BLINK_PERIOD_MS);
        }
    }

    HAL_GPIO_WritePin(LD2_GPIO_Port, LD2_Pin, GPIO_PIN_RESET);
}

/* =========================================================================
 * Audio Tone Generation & Playback
 * =========================================================================*/

/**
 * @brief  Pre-compute a 1 kHz sine wave into @ref beepBuffer (12-bit DAC scale).
 */
static void GenerateBeepTone(void)
{
    for (uint32_t i = 0; i < BEEP_SAMPLES; i++)
    {
        float t = (float)i / (float)SAMPLE_RATE_HZ;
        float s = sinf(2.0f * (float)M_PI * (float)BEEP_FREQ_HZ * t);
        beepBuffer[i] = (uint16_t)((s + 1.0f) * 2047.5f);
    }
}

/**
 * @brief  Pre-compute a 300 Hz 50% duty-cycle square wave into @ref buzzBuffer.
 */
static void GenerateBuzzTone(void)
{
    uint32_t halfPeriod = SAMPLE_RATE_HZ / (2u * BUZZ_FREQ_HZ);

    for (uint32_t i = 0; i < BUZZ_SAMPLES; i++)
    {
        buzzBuffer[i] = ((i / halfPeriod) % 2u == 0u) ? 4095u : 0u;
    }
}

/**
 * @brief  Stream an audio buffer to DAC1 channel 1 via DMA.
 * @param  buffer  Pointer to 12-bit DAC samples.
 * @param  length  Number of samples.
 *
 * @note   Uses a blocking HAL_Delay for simplicity. For production code,
 *         replace with a DMA-complete callback to avoid blocking the CPU.
 */
static void PlaySound(const uint16_t *buffer, uint32_t length)
{
    HAL_DAC_Start(&hdac1, DAC_CHANNEL_1);

    HAL_DMA_Start(&hdma_dac_ch1,
                  (uint32_t)buffer,
                  (uint32_t)&DAC1->DHR12R1,
                  length);

    SET_BIT(DAC1->CR, DAC_CR_DMAEN1);

    /* Wait for the waveform to finish playing */
    uint32_t durationMs = (length * 1000u) / SAMPLE_RATE_HZ;
    HAL_Delay(durationMs);

    /* Clean up */
    CLEAR_BIT(DAC1->CR, DAC_CR_DMAEN1);
    HAL_DMA_Abort(&hdma_dac_ch1);
    HAL_DAC_Stop(&hdac1, DAC_CHANNEL_1);
}

/* =========================================================================
 * Debug Utility
 * =========================================================================*/

/**
 * @brief  Transmit a null-terminated string over USART2 (blocking).
 *         Compile with DEBUG_UART_ENABLED=0 to remove all UART overhead.
 */
static void System_DebugLog(const char *msg)
{
#if DEBUG_UART_ENABLED
    HAL_UART_Transmit(&huart2,
                      (const uint8_t *)msg,
                      (uint16_t)strlen(msg),
                      100u);
#else
    (void)msg;
#endif
}
